### PR TITLE
[fix] Quote file separator string before using it as regular expression

### PR DESCRIPTION
**Pull request by smee**
Windows uses backslashes as file separators. Backslashes aren't valid regular expressions, though. By explicitely quoting the string before using it to create a regular expression we ensure that this code works under Windows, too.

### CODE REVIEW

**Comment by zcaudate** [comment]
please check failures

**Comment by smee** [comment]
Ok, this seems to be trickier than initially thought. The problem has two parts: First, I suggest replaceing all instances of ".replaceAll" (regex parameters) with ".replace" (string parameters). Since these calls never rely on any specific regular expression this eliminates all problems with backslashes under Windows.
The second problem is more severe: After fixing the first problem I get a lot of test failures because paths to jars in the local maven repository have mixed file separators. I'm looking into it, but this might take a while.

**Comment by zcaudate** [comment]
hahaha… yeah… this quoting and unquoting is serious business…

**Comment by smee** [comment]
I need to postpone working on this, sorry. There are more problems with supporting windows than previously thought. In general, the code tends to assume that the file separator is a forward slash. For example the function `vinyasa.maven/maven-coordinate` is supposed to work for symbol strings as well as paths. The problem is that only paths may use backslashes as separators, symbols always use slashes. 
For now, I will just use linux. Sorry for the fuzz.

**Comment by noncom** [comment]
Huh, guys, you seem to overcomplicate the thing. You can simply assume `/` as a file separator for paths on Windows, it will just work.  So, it should be in pseudocode:

`(.replaceAll group "\\." (if windows? "/" file/*sep*))`

or, if you still want this:

    (let [sep file/*sep*
          sep (if (= "\\") "\\\\" sep)]
      (.replaceAll group "\\." sep)

both do not seem too beautiful, but the first one can be used for the IRL situation where you don't actually get anything besides Linux and Windows, and the second solution also accounts for a hypothetical OS that still uses `\` as a separator, but will not accept `/` (Windows will).

**Comment by zcaudate** [comment]
@noncom: yeah i don't understand what the best way of doing this is. There should be a very simple solution for this...

**Pull request closed without merging**
